# 1. 数据库连接地址 (使用 H2 文件持久化存储)
# 注意：一定要确保 file: 后面没有多余的空格
spring.datasource.url=jdbc:h2:file:./data/taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. 自动根据 Java 代码生成数据库表
spring.jpa.hibernate.ddl-auto=update

# 3. 开启 H2 数据库的控制台预览
spring.h2.console.enabled=true
# 允许 H2 控制台被网页访问
spring.h2.console.settings.web-allow-others=true